apiVersion: v1
kind: Secret
metadata:
  name: supply-chain-overlay-secret
  namespace: tap-install
stringData:
  supply-overlay.yaml: |
    #@ load("@ytt:data", "data")
    #@ load("@ytt:overlay", "overlay")
    #@ supply_chains = overlay.subset({"kind":"ClusterSupplyChain"})
    #@ not_package = overlay.not_op(overlay.or_op(overlay.subset({"metadata": {"name": "basic-image-to-url-package"}}), overlay.subset({"metadata": {"name": "source-to-url-package"}})))
    #@overlay/match by=overlay.and_op(supply_chains, not_package), expects="1+"
    ---
    spec:
      resources:
      #@overlay/merge
      - name: deliverable-config
        templateRef:
          kind: ClusterTemplate
          name: external-deliverable-template
        params:
          - name: registry
            value: #@ data.values.registry
          - name: gitImplementation
            default: #@ data.values.git_implementation
