---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: generic-execute-alpine-run
spec:
  taskRef:
    resolver: cluster
    params:
      - name: kind
        value: task
      - name: namespace
        value: tap-tasks
      - name: name
        value: generic-execute-alpine
  params:
    - name: command
      value: date
