apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: example-using-appsso-binding
  labels:
    apps.tanzu.vmware.com/workload-type: web
    #apps.tanzu.vmware.com/has-tests: "false"
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    app.kubernetes.io/part-of: example-using-appsso-binding
spec:
  build:
    env:
      - name: BP_JVM_VERSION
        value: "17"
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
  serviceClaims:
  - name: appsso
    ref:
      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
      kind: ClassClaim
      name: appsso-claim
  source:
    git:
      url: https://github.com/evoila/tap-workshop/tree/main
      ref:
        branch: main
      subPath: using-appsso