apiVersion: v1
kind: Secret
metadata:
  name: # Name for the Secret #this is a name of a secret for accessing the workload in the repository
  annotations:
    tekton.dev/git-0: https://github.com #or https://gitlab.com
type: kubernetes.io/basic-auth #the type of a secret is needed. it could also be Opaque.
stringData:
  username: # Name of user that created the token
  password: # Token Value eg github_pat_...
