apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: workload-name
  labels:
    apps.tanzu.vmware.com/workload-type: web
    #apps.tanzu.vmware.com/has-tests: "false"
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    app.kubernetes.io/part-of: workload-name
    apis.apps.tanzu.vmware.com/register-api: "true"
spec:
  env:
    - name: SERVER_URL
      value: "http://${WORKLOAD_NAME}.${NAMESPACE}.svc.cluster.local:8080"
  build:
    env:
      - name: BP_JVM_VERSION
        value: "17"
  params:
  - name: catalog_path
    value: none
  - name: gitops_ssh_secret
    value: #name of the referenced secret
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/evoila/tap-workshop/tree/main
      ref:
        branch: main
    subPath: Example-Java-Application
