apiVersion: accelerator.apps.tanzu.vmware.com/v1alpha1
kind: Accelerator
metadata:
  name: workshop
  namespace: accelerator-system
spec:
  git:
    url: https://github.com/JanKraut/tap-workshop/
    ref:
      branch: main
    subPath: accelerator/