---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: mariadbs.evoila.de
spec:
  connectionSecretKeys:
  - provider
  - type
  - host
  - port
  - database
  - username
  - password
  group: evoila.de
  names:
    kind: MariaDB
    plural: mariadbs
  versions:
  - name: v1alpha1
    referenceable: true
    schema:
      openAPIV3Schema:
        properties:
          spec:
            description: The OpenAPIV3Schema of this Composite Resource Definition.
            properties:
              storageGB:
                default: 1
                description: The desired storage capacity of the database, in Gigabytes.
                type: integer
            type: object
        type: object
    served: true